- name: Download kafka
  get_url:
    url: https://apache-mirror.rbc.ru/pub/apache/kafka/2.6.1/kafka_2.12-2.6.1.tgz
    dest: /tmp/kafka.tgz
    force_basic_auth: yes

- name: Extract
  ansible.builtin.unarchive:
    src: /tmp/kafka.tgz
    dest: /opt/
    remote_src: yes

- name: Copy zookeper unit
  ansible.builtin.copy:
    src: "{{file_location2}}/zookeeper.service"
    dest: /etc/systemd/system/zookeeper.service

- name: Copy kafka unit
  ansible.builtin.copy:
    src: "{{file_location2}}/kafka.service"
    dest: /etc/systemd/system/kafka.service
    
- name: Reload Units
  shell: systemctl daemon-reload 

- name: Start service zookeper
  ansible.builtin.service:
    name: zookeeper
    state: started
    enabled: yes 
    
- name: Start service kafka
  ansible.builtin.service:
    name: kafka
    state: started
    enabled: yes 
